import Image from "next/image";
import { ArrowRight, Check, Clock3, FileCheck2, Fingerprint, LockKeyhole, Phone, ShieldCheck, Sparkles, UserRoundCheck } from "lucide-react";
import { services, contact } from "@/lib/constants";

export function TrustBar() {
  const items = [{icon:ShieldCheck,title:"KRA Compliance Expertise",copy:"Stay compliant, stay secure."},{icon:LockKeyhole,title:"Confidential & Trusted",copy:"Your information is handled with care."},{icon:Clock3,title:"Timely & Efficient",copy:"We respect your time."},{icon:UserRoundCheck,title:"Personalized Solutions",copy:"Tailored support for your needs."}];
  return <section className="trust-bar" aria-label="Our commitments"><div className="shell trust-grid">{items.map(({icon:Icon,title,copy}) => <div className="trust-item" key={title}><Icon /><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></section>;
}

export function Services() { return <section className="section services" id="services"><div className="shell">
  <div className="section-heading"><p className="eyebrow">WHAT WE DO</p><h2>Tax support that keeps<br/><em>you moving forward.</em></h2><p>Practical tax and compliance solutions for individuals, entrepreneurs and growing businesses.</p></div>
  <div className="services-grid">{services.map((service, index) => { const Icon = service.icon; return <article className="service-card" key={service.title}><span className="service-number">0{index + 1}</span><div className="icon-disc"><Icon aria-hidden="true" /></div><h3>{service.title}</h3><p>{service.description}</p><ul>{service.items.map(item => <li key={item}><Check aria-hidden="true" />{item}</li>)}</ul><a href="/#contact">Discuss this service <ArrowRight aria-hidden="true" /></a></article>; })}</div>
</div></section>; }

export function About() { return <section className="section about" id="about"><div className="shell about-grid">
  <div className="about-images"><div className="about-image"><Image src="/images/rg-consulting-hero.png" alt="Financial planning and accounting workspace" fill sizes="(max-width: 800px) 90vw, 42vw" /></div><div className="about-stamp"><Fingerprint/><span>Clear advice.<br/>Careful work.</span></div></div>
  <div className="about-copy"><p className="eyebrow">ABOUT RG CONSULTING</p><h2>Compliance should give you <em>confidence,</em> not stress.</h2><p>RG Consulting helps individuals, entrepreneurs and small businesses navigate Kenya’s tax and compliance requirements with clarity and confidence.</p><p>From KRA compliance and tax filing to business obligations, registrations, tax planning and ongoing assistance, we make every step easier to understand and manage.</p><blockquote>“Your compliance today,<br/>your peace of mind tomorrow.”</blockquote><a className="text-link" href="/#contact">Let’s discuss your needs <ArrowRight aria-hidden="true" /></a></div>
  </div></section>; }

export function WhyUs() { const reasons = [{icon:ShieldCheck,title:"KRA-Focused Expertise",copy:"Practical support tailored to Kenya’s tax environment."},{icon:LockKeyhole,title:"Confidential Service",copy:"Client information is handled professionally and privately."},{icon:FileCheck2,title:"Accurate Filing",copy:"Reduce the risk of errors, penalties and missed obligations."},{icon:Sparkles,title:"Personalized Guidance",copy:"Recommendations shaped around your circumstances."},{icon:Clock3,title:"Reliable Support",copy:"Support does not stop once a return has been submitted."}]; return <section className="section why" id="why-us"><div className="shell"><div className="section-heading section-heading--light"><p className="eyebrow">THE RG DIFFERENCE</p><h2>Why clients trust<br/><em>RG Consulting.</em></h2></div><div className="why-list">{reasons.map(({icon:Icon,title,copy},i)=><article key={title}><span>0{i+1}</span><Icon/><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>; }

export function Process() { const steps = [["Tell Us What You Need","Contact RG Consulting and explain your tax or compliance requirements."],["We Review Your Situation","We determine the appropriate filing, registration or advisory solution."],["We Handle the Process","Your compliance requirements are prepared accurately and efficiently."],["Stay Compliant","Receive continued guidance, reminders and support where required."]]; return <section className="section process" id="process"><div className="shell"><div className="section-heading"><p className="eyebrow">A SIMPLE PROCESS</p><h2>Clarity at <em>every step.</em></h2></div><div className="process-line">{steps.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>; }

export function ComplianceCTA() { return <section className="cta-band"><div className="cta-pattern" aria-hidden="true"/><div className="shell cta-inner"><div><p className="eyebrow">ACT BEFORE IT BECOMES URGENT</p><h2>Don’t wait for a KRA penalty to take compliance seriously.</h2><p>Get professional assistance with tax filing, registration and ongoing compliance requirements.</p></div><div className="cta-actions"><a className="button button--gold" href="/#contact">Talk to a Tax Consultant <ArrowRight aria-hidden="true" /></a><a className="call-link" href={`tel:${contact.phone}`}><Phone aria-hidden="true"/>Call {contact.phoneDisplay}</a></div></div></section>; }
